---
# tasks file for webserver
- name: update 
  apt: update_cache=yes

- name: Install NGINX
  apt: 
    name: nginx
    state: present

- name: Start NGINX
  systemd:
    name: nginx
    state: started
    enabled: yes
  register: result

- name: Show result
  debug:
    msg: "{{ result }}"

- name: Remove deafult nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    
- name: Create directory
  file:
    path: /var/www/test.com/html
    state: directory
    mode: 0755

- name: Create index html
  copy:
    src: "index.html"
    dest: /var/www/test.com/html/index.html
    mode: 0644

- name: Copy vhost
  copy:
    src: "vhost.conf"
    dest: /etc/nginx/sites-available/test.com

- name: Enable default nginx website
  file:
    src: /etc/nginx/sites-available/test.com
    path: /etc/nginx/sites-enabled/test.com
    state: link
  notify: 
    - restart nginx

- name: Append test.com to local DNS
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 test.com"
    state: present
